// Keyed by "MM-DD" for fixed holidays. Lunar holidays are set for 2025.
export const SPECIAL_DAYS = {
    "01-01": { emoji: "🎆", name: "New Year's Day" },
    "01-14": { emoji: "🪁", name: "Makar Sankranti" },
    "01-26": { emoji: "🇮🇳", name: "Republic Day" },
    "02-14": { emoji: "💝", name: "Valentine's Day" },
    "03-14": { emoji: "🎨", name: "Holi" },
    "04-03": { emoji: "✝️", name: "Good Friday" },
    "04-14": { emoji: "🙏", name: "Dr. Ambedkar Jayanti" },
    "05-01": { emoji: "✊", name: "Labour Day" },
    "06-21": { emoji: "🧘", name: "International Yoga Day" },
    "08-15": { emoji: "🇮🇳", name: "Independence Day" },
    "08-16": { emoji: "🪔", name: "Janmashtami" },
    "08-27": { emoji: "🐘", name: "Ganesh Chaturthi" },
    "10-02": { emoji: "🕊️", name: "Gandhi Jayanti & Dussehra" },
    "10-20": { emoji: "🪔", name: "Diwali" },
    "10-31": { emoji: "🎃", name: "Halloween" },
    "11-01": { emoji: "🌸", name: "Kannada Rajyotsava" },
    "11-05": { emoji: "🌾", name: "Guru Nanak Jayanti" },
    "12-25": { emoji: "🎄", name: "Christmas" },
    "12-31": { emoji: "🎉", name: "New Year's Eve" },
};
